### ISSUE TITLE
Missiles can pierce shields/circumvent shieldgating

### ISSUE THREAD

**Issue by FJonske** [TheStarport/freelancer-bmod#123]
Not quite sure how to reproduce this issue, but I have noticed this multiple times now, and always from the same source - Gunship Freighter missiles (after the gunships died). It's also not all possible damage that carries over, just a small amount, but enough to be noticeable. 

Originally I thought this was just me not noticing that there is more than one missile or that I took damage during an engagement, but now I am sure it's not - I just cleaned out a gunship spawn without losing health and all that remained was a missile in the rearview mirror, so I am 99.9% sure. Thought I'd just ignore it and keep flying. It hits, and takes out my shields and two pips of health, which on a Falcon is something like 2k damage. Judging by the damage, it can't have been two missiles stuck together, because Fleet LRMs or ASMFRs would have absolutely gutted me in that case. It has to either be some sort of bleed through shields (unlikely, as I think shields gating damage is hardcoded in the game, or maybe you take the regular hit and latency makes it so you fly through the explosion's AOE "a second time", so to speak?

**Comment by IrateRedKite** [comment]
Did some digging and there's unfortunately not much we can do about this. It is indeed tied to latency, and refactoring FL's netcode is definitely outside of our expertise! There might be some improvements in FLHook in the future that mitigate this, but this is outside of our power to consistently fix at the moment, sorry!
