### ISSUE TITLE
Manual merge request: Ace AI

### ISSUE THREAD

**Issue by FJonske** [TheStarport/freelancer-bmod#163]
As discussed previously with IRK.

In addition to the merge of the existing .ini modifications, we should look at the following things:
- The Ace Falcon needs a proper screen name.
- We might want a different ship model, e.g. the Fighting Falcon or Nerva's <REDACTED>.
- The more information from the ship and weapons we can hide, the better. Players need not know how badly I let the AI cheat.
- Add the modified Scorpion+ as Adder or a Scorpion+ but with a different internal name, and stats possibly obscured.
- Move the ace's spawn area from the testing zone to the Hudson gate debris field.
- Add encounters for Solo Ace (66%), Ace + Elite (17%), Ace + 2 Elites (17%).
- Add the respective pilot and bounty voucher as items.

If you tell me where the images for the pilot items are hiding, I'll make a sort of platinum rank symbol for captured ace pilots.

**Comment by IrateRedKite** [comment]
> If you tell me where the images for the pilot items are hiding, I'll make a sort of platinum rank symbol for captured ace pilots.

You can use [librelancer's SDK ](https://librelancer.net/downloads.html)to extract and then recompile icon entries. That said, I think we'd quite like a new icon for vouchers generally as we're using a placeholder one that seems to have been intended for the game's DRM failing to initialize! You can find the backgrounds we've been using for everything else in the XCF file in the root of the repository.
