### ISSUE TITLE
Consistent [+]/[-] gear nomenclature and icons

### ISSUE THREAD

**Issue by FJonske** [TheStarport/freelancer-bmod#176]
Noticed that a lot of gear is inconsistent in naming conventions and icons. I am willing to do the legwork on this, but I do need someone to put their foot down and declare a standard for how it will be done from now on, or else I will just worsen the problem.

@IrateRedKite @Beaglerush

**Comment by IrateRedKite** [comment]
Hard agree we need to get this sorted out. I know we have some icon variance (blue/yellow + signs, etc) but in terms of naming are there discrepancies? We should sit down and try to hammer this out sooner rather than later before more gear is added.

**Comment by IrateRedKite** [comment]
Would like to add that we might want to extend this project to internal naming and roll #99 and other cleanup issues into this

**Comment by IrateRedKite** [comment]
This has been solved in https://github.com/better-modernized-combat/bmod-client
