### ISSUE TITLE
Reorder Infocard XML Sheet

### ISSUE THREAD

**Issue by IrateRedKite** [TheStarport/freelancer-bmod#92]
Right now our infocard XML sheet is a mess. At some point I want to appropriately re-order and allocate blocks for infocards. This will require pretty extensive ini editing as things get reassigned.

I'd suggest we have blocks of 5000, allocated to each NAME and INFOCARD category that we decide. Each file uses a 16-bit index, so we have 65,536 entries to work within.

**Comment by FJonske** [comment]
I've started to work on this now (see: https://github.com/TheStarport/freelancer-bmod/commit/aa31608e670e717c45d19fdc2cad6c1781265a13).

The plan is as follows:
- Assign everything to blocks (block size and granularity are open to discussion)
- Save that mapping
- Automatically group strings in a block that look similar (script coming). If impossible, manually reorder, and automatically update the mapping
- Recursively grab every .ini file, update any line with an "_id" or "_info" in it according to mapping (script coming)
- Figure out where else strings from the XML are referenced and update those as well, this one is probably manual work
- Complete the mother of all merges.

My current plan for blocks are blocks of size 32768 (2^15) with one block for each of the following:
- Equipment
- Commodities
- NPCs
- UI
- Solars/Map
- News
- Rumors
- Missions
New IDs start at 524288 (2^19), the nearest power of two we have not used yet. Blocks are demarkated with an XML comment reading **.

@IrateRedKite If you find out what the maximum number of custom strings we can have is, and whether it actually influences the choice of block size, please let me know. Similarly, if there is a maximum ID, also let me know.

**Comment by IrateRedKite** [comment]
It's a it's 16-bit index per file with a total of 65,536 distinct values from whatever our DLL starts at (will check this in the evening when I'm off-shift) I would say reserve the first 1000 entries as well just in case.

**Comment by IrateRedKite** [comment]
This has been (somewhat) solved with the implementation of a new infocard system in https://github.com/better-modernized-combat/bmod-client/issues
